# -*- coding: utf-8 -*-
"""202255151_육한결_학생1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12NJPrxQx4OwYuJM4mMnk93XW3jVLewoA
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install beautifulsoup4
!pip install requests

from google.colab import drive
drive.mount('/content/drive')
# %cd /content/drive/MyDrive/Crawling
!pwd
!ls

import requests
from bs4 import BeautifulSoup
import csv
import time

def to_eng():
  while True:
    keyword = input('스포츠, 사회, 정치, 문화, 경제 중 하나를 선택해주시오: ')
    if keyword == '스포츠':
      eng = 'sports'
      return eng
    elif keyword == '사회':
      eng = 'society'
      return eng
    elif keyword == '정치':
      eng = 'politics'
      return eng
    elif keyword == '문화':
      eng = 'culture'
      return eng
    elif keyword == '경제':
      eng = 'economy'
      return eng
    else:
      print('스포츠, 사회, 정치, 문화, 경제 중 하나를 입력해주시오.')
      continue

f = open("data.csv", "w", encoding='utf-8')
writer = csv.writer(f) 
data = [['한겨레', '중앙일보', '한국일보', '동아일보']]
writer.writerows(data)

eng = to_eng()

for i in data[0]:

  #한겨레 기사
  if i == '한겨레':

    한겨레 = []

    url = f'https://www.hani.co.kr/arti/{eng}/home01.html'
    response = requests.get(url)

    if response.status_code == 200:
      html = response.text
      soup = BeautifulSoup(html, 'html.parser')
      
      title = soup.find_all('h4', {'class': 'article-title'}, 'a')
      for item in title:
        한겨레.append(item.get_text().strip('\n'))

      print(한겨레)

    else:
      print('연결되지않음')
      print(response.status_code)

    time.sleep(2)



  #중앙일보 기사
  if i == '중앙일보':

    중앙일보 = []

    url = f'https://www.joongang.co.kr/{eng}'
    response = requests.get(url)

    if response.status_code == 200:
      html = response.text
      soup = BeautifulSoup(html, 'html.parser')
          
      
      title = soup.find_all('h2', {'class': 'headline'}, 'a')
      for item in title:
        중앙일보.append(item.get_text().replace('&apos', '').strip('\n'))

      print(중앙일보)

    else:
      print('연결되지않음')
      print(response.status_code)

    time.sleep(2)





    else:
      print('연결되지않음')
      print(response.status_code)

    time.sleep(2)

num = min(len(한겨레), len(중앙일보))

for i in range(num):
    row = [[한겨레[i], 중앙일보[i]]]
    writer.writerows(row)

f.close()